position: "bottom"
height: 42
anchor_to_edges: true
icon_theme: "Papirus"

start:
  - type: "launcher"
    show_names: false
    show_icons: true

center:
  - type: "workspaces"
    hidden: [
      "special:scratchpad"
    ]
    all_monitors: false

end:
  - format:
    - ' {cpu_percent}% | {temp_c:coretemp-Package-id-0}°C'
    - ' ({memory_percent}%)'
    - ' ({disk_percent:/}%)'
    - '李 {net_down:eno1} / {net_up:eno1} Mbps'
    interval:
      cpu: 1
      disks: 300
      memory: 30
      networks: 3
      temps: 5
    type: sys_info
  - type: "tray"
  - type: "clock"
    format: "%d/%m/%Y %H:%M"
