#!/usr/bin/env bash

workspace() {
  # Get active workspace for this monitor
  echo `hyprctl activeworkspace -j`
}

workspace
socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r; do
workspace
done
