#!/usr/bin/env bash

eww close calendar || (\
    eww update day="`scripts/time_info --day`"; \
    eww update month="`scripts/time_info --month`"; \
    eww update year="`scripts/time_info --year`"; \
    eww open calendar --screen $MAIN_MONITOR_ID)
