#!/usr/bin/env bash

workspaces() {
  # Get workspaces for this monitor
  echo `hyprctl workspaces -j | jq '[.[] | select(.name | test("special:") | not)] | sort_by(.id)'`
}

workspaces
socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r; do
workspaces
done